<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>dibiorm</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" media="screen" type="text/css" href="{$baseUri}styles/fshl_COHEN_style.css">
  </head>
  <body>

{block|texy}

This is it ! Finest PHP ORM out there, based on Dibi
*************************************************

"default (model testing)":{link Default:default} |
"syncdb":{link Default:syncdb} |
"sqlall":{link Default:sqlall} |
"sqlclear":{link Default:sqlclear}

now in: {$control->getAction()}
==============================

{/block}


{block content}{/block}
      
  </body>
</html>
