{extends $layout}
{block #content}
{if !$sql}
{block|ansi_console_colors}Model and database %9%rin sync%n, nothing to be executed.{/block}
{elseif $confirm}

Executed code:

{!$sql|fshl_highlighter|ansi_console_colors}
{else}

Model and database out of sync, execute SQL code to synchronize:

{!$sql|fshl_highlighter|ansi_console_colors}

{if !$confirm}{block|ansi_console_colors}Run tool with %9--confirm%n option to execute SQL code{/block}{/if}
{/if}
{/block}